#ifndef RG16_MOZAIK_COLOR_SPHERE_HPP
#define RG16_MOZAIK_COLOR_SPHERE_HPP

#include <GL/glew.h>
#include <glm/vec3.hpp>

/** Create a sphere approximation based on octahedron "inflation"
 *
 * The sphere is generated by dividing octahedron sides into smaller
 * triangles, and then normalizing their distance from the center.
 *
 * @param center
 * Center of the resulting sphere.
 * @param diameter
 * Diameter of the resulting sphere.
 * @param lod
 * Level of detail - determines the number of separate edges per side of the sphere.
 * @return
 * Pointer to the resulting array of sphere vertices, which should be
 * deallocated manually.
 */
GLfloat* create_sphere(glm::vec3 center, GLfloat diameter, unsigned lod);

#endif //RG16_MOZAIK_COLOR_SPHERE_HPP
